/********************************************************************************************************/
CREATE TABLE TMP(
    NOMBRE_VICTIMA           VARCHAR2(250) NULL,
    APELLIDO_VICTIMA         VARCHAR2(250) NULL,
    DIRECCION_VICTIMA        VARCHAR2(250) NULL,
    FECHA_PRIMERA_SOSPECHA   VARCHAR2(250) NULL,
    FECHA_CONFIRMACION       VARCHAR2(250) NULL,
    FECHA_MUERTE             VARCHAR2(250) NULL,
    ESTADO_VICTIMA           VARCHAR2(250) NULL,
    NOMBRE_ASOCIADO          VARCHAR2(250) NULL,
    APELLIDO_ASOCIADO        VARCHAR2(250) NULL,
    FECHA_CONOCIO            VARCHAR2(250) NULL,
    CONTACTO_FISICO          VARCHAR2(250) NULL,
    FECHA_INICIO_CONTACTO    VARCHAR2(250) NULL,
    FECHA_FIN_CONTACTO       VARCHAR2(250) NULL,
    NOMBRE_HOSPITAL          VARCHAR2(250) NULL,
    DIRECCION_HOSPITAL       VARCHAR2(250) NULL,
    UBICACION_VICTIMA        VARCHAR2(250) NULL,
    FECHA_LLEGADA            VARCHAR2(250) NULL,
    FECHA_RETIRO             VARCHAR2(250) NULL,
    TRATAMIENTO              VARCHAR2(250) NULL,
    EFECTIVIDAD              NUMBER NULL,
    FECHA_INICIO_TRATAMIENTO VARCHAR2(250) NULL,
    FECHA_FIN_TRATAMIENTO    VARCHAR2(250) NULL,
    EFECTIVIDAD_EN_VICTIMA   NUMBER NULL
);
/********************************************************************************************************/



